# Fungsi

- Sudah pernah kita gunakan
- contoh: type()
- Kumpulan code yang digunakan kembali
- Menyelesaikan tugas yang spesifik
- Panggil fungsi yang sudah ada daripada harus membuat sendiri dari awal

In [1]:
keluarga = [1.73, 1.68, 1.71, 1.89]

In [2]:
keluarga

[1.73, 1.68, 1.71, 1.89]

In [4]:
max(keluarga)

1.89

In [5]:
paling_tinggi = max(keluarga)

In [6]:
paling_tinggi

1.89

In [10]:
len(keluarga)

4

In [7]:
round(1.68, 1)

1.7

In [8]:
round(1.68)

2

In [9]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



## Fungsinya apa aja?

- Kalau fungsi standar biasanya sudah disediakan misal max, min, sum dll
- Internet adalah teman anda

## Fungsi Built-in

- Maksimum dari list: max()
- panjang dari list: len()
- Mendapatkan index dari list: ?
- Me *reverse* list: ?

## Method


In [1]:
adik = 'dian'                         # Object     tipe: str     contoh method: capitalize(), replace()

tinggi = 1.73                         # Object     tipe: float   contoh method: bit_length(), conjugate()

keluarga = [1.73, 1.68, 1.71, 1.89]   # Object     tipe: list    contoh method: index(), count()

## List Method

In [2]:
keluarga = ["kakak", 1.73, "adik", 1.68, "ibu", 1.71, "ayah", 1.89]

In [4]:
keluarga.index('adik')

2

In [6]:
keluarga.count(1.73)

1

## Str Method

In [7]:
adik

'dian'

In [8]:
adik.capitalize()

'Dian'

In [9]:
adik.replace('i', 'y')

'dyan'

- Semua dalam Python merupakan Object
- Setiap Object memiliki method yang sesuai dengan objectnya

In [10]:
adik.replace('i', 'y')

'dyan'

In [11]:
keluarga.replace('ibu', 'mama')

AttributeError: 'list' object has no attribute 'replace'

In [12]:
adik.index('a')

2

In [13]:
keluarga.index('ibu')

4

In [14]:
keluarga.append('saya')

In [15]:
keluarga

['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89, 'saya']

In [19]:
keluarga.append(1.76)

In [22]:
keluarga

['kakak', 1.73, 'adik', 1.68, 'ibu', 1.71, 'ayah', 1.89, 'saya', 1.76]

## Ingat

### fungsi

In [23]:
type(keluarga)

list

### method: merupakan fungsi pada object

In [24]:
keluarga.index('ibu')

4

## Package

- Fungsi dan Method sangat *powerfull*
- Semua kode dalam satu Python?

Apakah Package / Paket itu?

- Sebuah direktory Script Python
- Setiap Script = Modul
- Mempunyai fungsi , method, tipe yang spesifik
- Ribuan Paket Tersedia tergantung keperluan
- Contoh: NumPy, Matplotlib, Scikit-learn

## Install Package

- Jika kamu menggunakan anaconda maka semua paket untuk keperluan Data Science sudah tersedia
- Jika kamu ingin mencoba install Python dari awal maka ada dua kemungkinan
- 1. pip belum tersedia, 2. pip sudah tersedia
- Jika belum tersedia download di http://pip.readthedocs.org/en/stable/installing/
- download get-pip.py
- Buka Terminal / CMD
- python3 get-pip.py (Linux/MacOS) python get-pip.py (windows)
- Untuk menginstall numpy
- pip3 install numpy (Linux/MacOS) pip install numpy (windows)

## import package

In [25]:
import numpy

In [26]:
array([1,2,3])

NameError: name 'array' is not defined

In [27]:
numpy.array([1,2,3])

array([1, 2, 3])

In [28]:
import numpy as np

In [29]:
np.array([1,2,3])

array([1, 2, 3])

In [30]:
from numpy import array

In [31]:
array([1,2,3])

array([1, 2, 3])

### from numpy import array

In [35]:
from numpy import array

keluarga = ["kakak", 1.73, "adik", 1.68, "ibu", 1.71, "ayah", 1.89]

keluarga_tambahan = keluarga + ['saya', 1.76]

print(str(len(keluarga_tambahan)) + " elemen pada keluarga_tambahan")

np_keluarga = array(keluarga_tambahan) # Menggunakan Numpy, tapi tidak begitu jelas

print(np_keluarga)

10 elemen pada keluarga_tambahan
['kakak' '1.73' 'adik' '1.68' 'ibu' '1.71' 'ayah' '1.89' 'saya' '1.76']


### import numpy as np

In [36]:
import numpy as np

keluarga = ["kakak", 1.73, "adik", 1.68, "ibu", 1.71, "ayah", 1.89]

keluarga_tambahan = keluarga + ['saya', 1.76]

print(str(len(keluarga_tambahan)) + " elemen pada keluarga_tambahan")

np_keluarga = np.array(keluarga_tambahan) # Jelas menggunakan Numpy dengan alias np

print(np_keluarga)

10 elemen pada keluarga_tambahan
['kakak' '1.73' 'adik' '1.68' 'ibu' '1.71' 'ayah' '1.89' 'saya' '1.76']
