# Numpy

## Mengingat list

- *powerfull*
- Koleksi dari nilai
- Menampung berbagai macam tipe data
- Mengganti, Menambah, Mengurangi
- Kebutuhan untuk Data Science: Operasi Matematika antar list, *speed*

In [1]:
tinggi = [1.73, 1.68, 1.71, 1.89, 1.69]

In [2]:
tinggi

[1.73, 1.68, 1.71, 1.89, 1.69]

In [3]:
berat = [65.4, 59.2, 63.6, 88.4, 68.7]

In [4]:
berat / tinggi ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## Solusi? Numpy, horray

- Python Numerik
- Alternatif dari list python: NumPy Array
- Kalkulasi semua elemen array
- Mudah dan Cepat

In [5]:
import numpy as np
np_tinggi = np.array(tinggi)
np_tinggi

array([ 1.73,  1.68,  1.71,  1.89,  1.69])

In [6]:
np_berat = np.array(berat)

In [7]:
np_berat

array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [8]:
bmi = np_berat / np_tinggi ** 2

In [9]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  24.05377963])

## Numpy remarks

In [10]:
np.array([1.0, 'is', True]) # Numpy hanya dapat menampung satu tipe

array(['1.0', 'is', 'True'], 
      dtype='<U32')

In [11]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [12]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [13]:
numpy_array + numpy_array 

array([2, 4, 6])

## Numpy subsetting

In [14]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  24.05377963])

In [15]:
bmi[1]

20.975056689342409

In [16]:
bmi > 23

array([False, False, False,  True,  True], dtype=bool)

In [17]:
bmi[bmi > 23]

array([ 24.7473475 ,  24.05377963])

## 2D Numpy arrays

In [18]:
import numpy as np
np_tinggi = np.array([1.73, 1.68, 1.71, 1.89, 1.69])
np_berat = np.array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [19]:
type(np_tinggi)

numpy.ndarray

In [20]:
type(np_berat)

numpy.ndarray

In [29]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.69], [ 65.4,  59.2,  63.6,  88.4,  68.7]])


In [22]:
np_2d

array([[  1.73,   1.68,   1.71,   1.89,   1.69],
       [ 65.4 ,  59.2 ,  63.6 ,  88.4 ,  68.7 ]])

In [23]:
np_2d.shape

(2, 5)

In [26]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.69], [ 65.4,  59.2,  63.6,  88.4,  "68.7"]])

In [27]:
np_2d # Ingat hanya bisa satu tipe

array([['1.73', '1.68', '1.71', '1.89', '1.69'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], 
      dtype='<U32')

## Nubsetting Numpy 2D

In [30]:
np_2d[0]

array([ 1.73,  1.68,  1.71,  1.89,  1.69])

In [31]:
np_2d[0][2]

1.71

In [32]:
np_2d[0,2]

1.71

In [33]:
np_2d[:,1:3]

array([[  1.68,   1.71],
       [ 59.2 ,  63.6 ]])

In [34]:
np_2d[1,:]

array([ 65.4,  59.2,  63.6,  88.4,  68.7])

## NumPy dan Statistika Dasar

In [35]:
tinggi = np.round(np.random.normal(1.75, 0.20, 5000), 2)
berat = np.round(np.random.normal(60.32, 15, 5000), 2)

# np.random.normal(distribution_mean, distribution_standard_deviation, jumlah_sample)

In [40]:
np_city = np.column_stack((tinggi, berat))

In [41]:
np_city

array([[  1.66,  64.44],
       [  1.74,  97.04],
       [  1.53,  64.79],
       ..., 
       [  1.69,  60.82],
       [  1.75,  74.59],
       [  1.59,  56.12]])

In [43]:
np.mean(np_city[:,0])

1.751852

In [44]:
np.median(np_city[:,0])

1.75

In [45]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[ 1.        , -0.00975972],
       [-0.00975972,  1.        ]])

In [46]:
np.std(np_city[:,0])

0.2013840363484653