## Mengingat NumPy

In [1]:
import numpy as np
np_tinggi = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_berat = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_berat / np_tinggi ** 2


In [2]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

In [4]:
bmi > 23

array([False, False, False,  True, False], dtype=bool)

In [5]:
bmi[bmi > 23]

array([ 24.7473475])

## Komparasi Numerik

In [6]:
2 < 3

True

In [7]:
2 == 3

False

In [8]:
2 <= 3

True

In [9]:
3 <= 3

True

In [10]:
x = 2

In [11]:
y = 3

In [12]:
x < y

True

## Komparasi yang lain

In [15]:
'dian' < 'diantemi'

True

In [16]:
3 < 'dian'

TypeError: '<' not supported between instances of 'int' and 'str'

In [17]:
3 < 4.1

True

In [18]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

In [19]:
bmi > 23

array([False, False, False,  True, False], dtype=bool)

In [ ]:
# < 
# <= 
# > 
# >= 
# == 
# !=

## Boolean Operator

In [20]:
# and, or, not

In [23]:
True and True

True

In [24]:
False and True

False

In [25]:
True and False

False

In [26]:
False and False

False

In [27]:
x = 12

In [29]:
x > 5 and x < 15

True

In [31]:
True or True

True

In [32]:
False or True

True

In [33]:
True or False

True

In [34]:
False or False

False

In [35]:
y = 5

In [37]:
y < 7 or y > 13

True

In [38]:
not True

False

In [39]:
not False

True

## Kembali ke NumPy

In [40]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

In [41]:
bmi > 21

array([ True, False,  True,  True,  True], dtype=bool)

In [42]:
bmi < 22

array([ True,  True,  True, False,  True], dtype=bool)

In [43]:
bmi > 21 and bmi <22

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
 np.logical_and(bmi > 21, bmi < 22) #np.logical_and np.logical_or np.logical_or

array([ True, False,  True, False,  True], dtype=bool)

In [45]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([ 21.85171573,  21.75028214,  21.44127836])

## if, elif, else (conditional statement)

In [47]:
z = 4
if z % 2 == 0 :
    print("z adalah genap")

z adalah genap


In [48]:
z = 4
if z % 2 == 0:
    print("Mengecek " + str(z))
    print("z adalah genap")

Mengecek 4
z adalah genap


In [50]:
z = 5 # TIDAK TEREKSEKUSI KARENA FALSE
if z % 2 == 0:
    print("Mengecek " + str(z))
    print("z adalah genap")

In [51]:
z = 5
if z % 2 == 0 :
    print("z adalah genap")
else :
    print("z adalah ganjil")

z adalah ganjil


In [ ]:
z = 3
if z % 2 == 0:
    print("z habis dibagi 2
elif z % 3 == 0:
    print("z habis dibagi 3
else :
    print("z is

:

divisible by 3")
neither divisible by 2 nor by 3")